### ISSUE TITLE
Objects not working (or user error?)

### ISSUE THREAD

**Issue by dwatts3624** [kenberkeley/vue-sync-query-mixin#3]
Hello!  Nice work on this mixin!

I've been trying to get a state who's value is a simple object working and starting to wonder if I'm implementing your module correctly.  From the code, I can see it supports objects so I know there's something there.

And I can see this does work (however when reloading the page it doesn't read the values):

```js
this.syncQuery([
  {
    localField: 'dateRange.end',
    queryField: 'endDate'
  },
  {
    localField: 'dateRange.start',
    queryField: 'startDate' 
  }
]);
```

Where this doesn't:
```js
this.syncQuery([
  {
    localField: 'dateRange',
    queryField: 'dateRange'
  }
]);
```

I was able to solve the issue of it loading the values when reloading the page or onpopstate with something like this (similar to `_.get()`)
https://stackoverflow.com/questions/13719593/how-to-set-object-property-of-object-property-of-given-its-string-name-in-ja

Which would look like this (and works for all other values):
```js
this.$watch(`$route.query.${queryField}`, function (v, oldV) {
  assign(this, localField, query2local.formatter(v, oldV) || defaultVal)
}, query2local)
```
_Note on above that I'd really need to integrate that into `Vue.set` for it to be workable since, as-is, it wouldn't trigger a state update_

But I'm just wondering if I'm missing something basic here.

And, of course, I could just split startDate and endDate but with the way my component's props are working that begins to make the code I'm using more complex since I have a few things bound directly to dateRange with `v-model` or `[something].sync`

**Comment by kenberkeley** [comment]
You might have to use your own fork, mate.
