### ISSUE TITLE
Module not found: Error: [CaseSensitivePathsPlugin]

### ISSUE THREAD

**Issue by arvx47** [kenberkeley/vue-sync-query-mixin#4]
There is a problem when using Webpack CaseSensitivePathsPlugin.

> Module not found: Error: [CaseSensitivePathsPlugin] `C:\<someAbsolutePath>\node_modules\vue-sync-query-mixin\es\utils\typeOf.js` does not match the corresponding path on disk `typeof.js`.

Fix could be renaming these files as how they are referenced.
![image](https://user-images.githubusercontent.com/13633641/73563026-2b64b180-443b-11ea-9ef9-310209c715b7.png)

**Comment by kenberkeley** [comment]
`npm i -S vue-sync-query-mixin@2.1.3`
